version: '3.8'
services:
  db:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}" ]
      interval: 3s
      timeout: 3s
      retries: 5

  app:
    build: .
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - 8000:8000